### ISSUE TITLE
Installing docset fails with Search failed: "too long"

### ISSUE THREAD

**Issue by fikovnik** [dash-docs-el/dash-docs#1]
I used the `counsel-dash-install-docset` with I understand is just an alias to `dash-docs-install-docset` to install `Emacs_Lisp` and it does fail with the following error:

```
Contacting host: api.github.com:443
Contacting host: raw.github.com:443
Wrote /tmp/Emacs_Lisp-feed.xml
Wrote /tmp/Emacs_Lisp-docset.tgz
dash-docs-extract-and-get-folder: Search failed: "too long"
```

I checked and it does download the docset, but then it never installs it. Do you know what might go wrong? I use the following configuration:

```elisp
(use-package counsel-dash
  :commands counsel-dash counsel-dash-install-docset
  :hook
  (emacs-lisp-mode-hook . (lambda () (setq-local counsel-dash-docsets '("Emacs Lisp"))))
  :custom
  (counsel-dash-docsets-path "~/.config/dash-docset"))
```

EDIT: the same happens when I try to install the downloaded tgz using `counsel-dash-install-docset-from-file`.

**Comment by kidd** [comment]
Hi @fikovnik, this error comes from `dash-docs-extract-and-get-folder` function. depending on how confortable you are with elisp, I'd advise to call it manually (use edebug or your favourite debugging technique). It needs the path to the tgz file, and there you should find out why the `tar` command is failing.

That code came from a recent PR that fixed a particular problem on windows, so maybe (just maybe) it is platform dependent (just something to take into account when debugging).

**Comment by fikovnik** [comment]
Thanks for the pointer. I debugged it and the problem was that I set `counsel-dash-docsets-path` to `~/.config/dash-docset`.

What would be great that in the case the tar process does not exit with 0, the content of the temp buffer is shown.

Thanks a lot for help.
