### ISSUE TITLE
Not working with Emacs 26.2?

### ISSUE THREAD

**Issue by scaramouche1** [dash-docs-el/dash-docs#3]
I recently upgraded Emacs to version 26.2 and dash-docs stopped working.  In particular `dash-docs-search` always returns `nil`.

I have tried adding a `.mode list` line to `~/.sqliterc` as well as removing this file altogether.  Any ideas?

**Comment by kidd** [comment]
did you upgrade from helm-dash to dash-docs also in the same move? maybe you have to update some var names... 

But nop,.. no idea what might be happening there. I've used dash-docs with 26.X and 27.X successfully

**Comment by scaramouche1** [comment]
Found the problem.  Now, instead of using the `helm-dash-*` variables, one needs to use the `dash-docs-*` configuration variables.   Also, it seems that `dash-docs` needs to be loaded before `helm-dash`.

I include my functioning `use-package` configuration in case it's useful:

    (use-package helm-dash
      :diminish
      :after helm
      :demand
      :bind ("C-h C-SPC" . helm-dash-at-point)
      :init
      (use-package dash-docs)
      (setq dash-docs-min-length 3)
      (setq dash-docs-browser-func 'eww)
      (setq dash-docs-docsets-path "/opt/zeal-docsets")
      :config
      (add-hook 'emacs-lisp-mode-hook '(lambda () (setq-local dash-docs-docsets '("Emacs_Lisp"))))
      (add-hook 'lisp-mode-hook       '(lambda () (setq-local dash-docs-docsets '("Common_Lisp"))))
      (add-hook 'slime-repl-mode-hook '(lambda () (setq-local dash-docs-docsets '("Common_Lisp"))))
      (add-hook 'sly-mrepl-mode-hook  '(lambda () (setq-local dash-docs-docsets '("Common_Lisp"))))
      (add-hook 'LaTeX-mode-hook      '(lambda () (setq-local dash-docs-docsets '("LaTeX"))))
      (add-hook 'web-mode-hook        '(lambda () (setq-local dash-docs-docsets '("HTML" "CSS"))))
      (add-hook 'python-mode-hook     '(lambda () (setq-local dash-docs-docsets '("Python_3" "SciPy" "NumPy"))))
      (add-hook 'sh-mode-hook         '(lambda () (setq-local dash-docs-docsets '("Bash"))))
    )
