### ISSUE TITLE
Also getting Installing docset fails with Search failed: "too long"

### ISSUE THREAD

**Issue by vv111y** [dash-docs-el/dash-docs#4]
As in #1  
- 4.19.66-1-MANJARO (up to date linux/arch).
- emacs 26.2
- spacemacs develop branch, + packages, all up to date

`dash-docs-docsets-path`, `helm-dash-docsets-path`, `helm-dash-docset-newpath`  
all set to `~/.docsets`  

I did a couple quick runs through `dash-docs-extract-and-get-folder`, but then I'm not sure what to look for.

**Comment by dvzubarev** [comment]
I stumbled upon this error too.
To see an actual error, you need to edit `dash-docs-extract-and-get-folder`:
- change `(search-backward "too long")` to `(search-backward "too long" nil t)`
- change 

`((not (equal result 0)) (error "Failed to extract %s to %s. Error: %s" docset-temp-path (helm-dash-docsets-path) result)))`

 to

 `((not (equal result 0)) (error "Failed to extract %s to %s. Code: %s, %s " docset-temp-path (dash-docs-docsets-path) result (buffer-string)))`


And you will see the error in `Messages`. 
In my case it was 

```
Failed to extract /tmp/PostgreSQL-docset.tgz to /home/denin/.local/share/Zeal/Zeal/docsets. Code: 2, /bin/tar: ~/.local/share/Zeal/Zeal/docsets: Cannot open: No such file or directory
/bin/tar: Error is not recoverable: exiting now
```
Then I read in the documentation to the `dash-docs-docsets-path` variable:

```
If you’re setting this option manually, set it to an absolute
path.  You can use ‘expand-file-name’ function for that.
```
So tar is unable to resolve `~`.
If you use Spacemacs you can change layer configuration:

```
(dash :variables
           helm-dash-docset-newpath (expand-file-name "~/.docsets"))
```

**Comment by vv111y** [comment]
Odd, it seems to be working even though your edits are only to get the error message. Just to be safe I will also use expand-file-name.   
Thanks for the help.
