### ISSUE TITLE
Handle "tarix" docsets?

### ISSUE THREAD

**Issue by ndw** [dash-docs-el/dash-docs#7]
I've only recently started using Dash, so I don't know if this is something new or not, but I've noticed several docsets that have compressed content. For example, if you explore the `Python 3` docset, you find this in the `Contents/Resources` directory:
```
-rw-r--r-- 1 ndw staff 3.7M Apr 18 07:06 docSet.dsidx
-rw-r--r-- 1 ndw staff  32K Apr 18 07:06 docSet.dsidx-shm
-rw-r--r-- 1 ndw staff 3.7M Apr 18 07:06 docSet.dsidx-wal
-rw-r--r-- 1 ndw staff  14M Apr 18 07:06 tarix.tgz
-rw-r--r-- 1 ndw staff 212K Feb 27 09:40 tarixIndex.db
```
Unsurprisingly, perhaps, `dash-docs` doesn't appear to be able to use those.

On a more positive note, `dash-docs` on MacOS with Emacs 27 seems to work just fine.

**Comment by kidd** [comment]
Hello, 
I'm installing 'Python 3' docset and see the normal structure: 

```
/home/rgrau/.docsets/Python 3.docset/Contents/Resources:
total used in ......
drwxr-xr-x 3 4.0K 2020-02-27 09:35 Documents
-rw-r--r-- 1  259 2020-02-27 09:40 LICENSE
-rw-r--r-- 1  174 2020-02-27 09:35 Nodes.xml
-rw-r--r-- 1 2.8M 2020-02-27 09:36 Tokens.xml
-rw-r--r-- 1 3.7M 2020-02-27 09:38 docSet.dsidx
-rw-r--r-- 1  15K 2016-04-27 00:49 docSet.mom
-rw-r--r-- 1 3.0M 2020-02-27 09:38 docSet.tokencache
-rw-r--r-- 1  32K 2020-02-27 09:39 docSet.dsidx-shm
-rw-r--r-- 1 3.7M 2020-02-27 09:38 docSet.dsidx-wal
```

I'm installing it with `m-x dash-docs-install-docset`. Are you installing them via the real Dash? maybe it's a change on the app side only...

**Comment by ndw** [comment]
Interesting. Yes, it's likely that I installed that one from the Dash app not emacs. And I've confirmed that you can unpack them by hand if necessary and they work. So I'll just close this.
