### ISSUE TITLE
logo?

### ISSUE THREAD

**Issue by kidd** [dash-docs-el/dash-docs#8]
Hey @gilbertw1, I created this very simple logo of dash-docs-el. Wanted to add it to the org, but I don't have the rights to change it. 

Could you add it? or give the the permissions and I'll do it when I have a minute.

Thanks!

![dash-docs-el](https://user-images.githubusercontent.com/25607/82128962-445d5c80-97b7-11ea-812d-f36dca02b76b.png)

**Comment by gilbertw1** [comment]
Looks good!

You should have the access you need to add it to the organization.

**Comment by kidd** [comment]
:+1: Changed!

If we want the originals somewhere, I can push them to the repo under `/extras`, or something. (I've no idea what I'm doing anyway)
